### ISSUE TITLE
Packaging and documentation conflicts

### ISSUE THREAD

**Issue by tonioo** [CptLemming/django-subcommand2#1]
Hi,
It looks like an older package using the same name is already distributed on PyPi, do you confirm that ?

Otherwise, the link you give to the online documenation on ReadTheDocs also corresponds to this older package.

Do you plan to release an official package soon ?

**Comment by CptLemming** [comment]
I think I used a cookie cutter to generate this project and forgot to check these things after pushing >.<

Looks like I'll have to rename the repo (django-subcommand2 perhaps). Don't see any reason not to publish if people would be interested in using it.

**Comment by tonioo** [comment]
I am interested and I plan to use it in one of my projects (https://github.com/tonioo/modoboa) but it would be better with a regular package.

**Comment by CptLemming** [comment]
Alright, renamed and published: https://pypi.python.org/pypi/django-subcommand2

Hope it proves useful to you!

**Comment by tonioo** [comment]
Great, thank you!
